name: SpaceKitSample Tests

on:
    pull_request:
      types: [opened, synchronize, reopened, ready_for_review]
      branches:
      - main
    workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer

jobs:
      Test:
        if: github.event.pull_request.draft == false
        name: Test
        runs-on: macos-12
        timeout-minutes: 60

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: SpaceKitSample tests
          run: exec ./.github/scripts/SpaceKitSample-all_tests.sh
