name: SpaceKitSample Tests

on:
    pull_request:
      types: [opened, synchronize, reopened, ready_for_review]
      branches:
      - main
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
      Test:
        if: github.event.pull_request.draft == false
        name: Test
        runs-on: [self-hosted, macOS]
        timeout-minutes: 60

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set Developer dir
          run: exec ./.github/scripts/set_build_settings.sh

        - name: SpaceKitSample tests
          run: exec ./.github/scripts/SpaceKitSample-all_tests.sh
