name: Update Cocoapod

on:
  push:
    branches:
    - main

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.framework }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          framework:
            - 'SpaceKit.xcframework/**'

  Update_Cocoapod:
    name: Update podspec version
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.framework == 'true' }}
    timeout-minutes: 60

    steps:
    - name: Set podspec version
      run: exec ./.github/scripts/set_podspec_version.sh

    - name: Add podspec tag
      run: exec ./.github/scripts/add_podspec_tag.sh
