name: Update SpaceKit SDK

on:
    workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer

jobs:
  open_pull_request:
    name: Open pull request
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Remove existing framework
      run: rm -rf SpaceKit.xcframework

    - name: Download SpaceKit.xcframework artifact
      run: |
        xcframework_artifact_id=$(gh api \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/DentReality/iOS-Hyper/actions/artifacts \
            --jq '[.artifacts[]|select(.name=="xcframework")][0].id')

        echo "Artifact ID: $xcframework_artifact_id"
        
        gh api \           
          -H "Accept: application/vnd.github.v3+json" \
          /repos/DentReality/iOS-Hyper/actions/artifacts/$xcframework_artifact_id/zip > xcframework.zip

        unzip xcframework.zip

        rm -rf xcframework.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Remove existing documentation archive
    #   run: rm -rf SpaceKit.doccarchive 

    # - name: Download SpaceKit.doccarchive artifact
    #   uses: actions/download-artifact@v3
    #   with:
    #     name: doccarchive

    # - name: Unzip documentation archive
    #   run: unzip doccarchive.zip
    
    - name: Create pull request
      uses: peter-evans/create-pull-request@v4